#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : asciidoc
Version  : 10.2.0
Release  : 55
URL      : https://files.pythonhosted.org/packages/8a/57/50180e0430fdb552539da9b5f96f1da6f09c4bfa951b39a6e1b4fbe37d75/asciidoc-10.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/8a/57/50180e0430fdb552539da9b5f96f1da6f09c4bfa951b39a6e1b4fbe37d75/asciidoc-10.2.0.tar.gz
Summary  : AsciiDoc is a text document format for writing things.
Group    : Development/Tools
License  : GPL-2.0+
Requires: asciidoc-bin = %{version}-%{release}
Requires: asciidoc-python = %{version}-%{release}
Requires: asciidoc-python3 = %{version}-%{release}
Requires: docbook-xml
Requires: libxml2-bin
Requires: libxslt
BuildRequires : buildreq-distutils3
BuildRequires : docbook-xml
BuildRequires : graphviz
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : source-highlight

%description
===========

%package bin
Summary: bin components for the asciidoc package.
Group: Binaries

%description bin
bin components for the asciidoc package.


%package python
Summary: python components for the asciidoc package.
Group: Default
Requires: asciidoc-python3 = %{version}-%{release}

%description python
python components for the asciidoc package.


%package python3
Summary: python3 components for the asciidoc package.
Group: Default
Requires: python3-core
Provides: pypi(asciidoc)

%description python3
python3 components for the asciidoc package.


%prep
%setup -q -n asciidoc-10.2.0
cd %{_builddir}/asciidoc-10.2.0
pushd ..
cp -a asciidoc-10.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656369112
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/a2x
/usr/bin/asciidoc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
