#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : asciidoc
Version  : 10.1.4
Release  : 49
URL      : https://files.pythonhosted.org/packages/8f/94/aa5be7907b9dd1733e4e7a1fa0bb737022d6fb13f80a9283520c66435f4d/asciidoc-10.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/8f/94/aa5be7907b9dd1733e4e7a1fa0bb737022d6fb13f80a9283520c66435f4d/asciidoc-10.1.4.tar.gz
Summary  : AsciiDoc is a text document format for writing things.
Group    : Development/Tools
License  : GPL-2.0
Requires: asciidoc-bin = %{version}-%{release}
Requires: asciidoc-python = %{version}-%{release}
Requires: asciidoc-python3 = %{version}-%{release}
Requires: docbook-xml
Requires: libxml2-bin
Requires: libxslt
BuildRequires : buildreq-distutils3
BuildRequires : docbook-xml
BuildRequires : graphviz
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : source-highlight

%description
===========

%package bin
Summary: bin components for the asciidoc package.
Group: Binaries

%description bin
bin components for the asciidoc package.


%package python
Summary: python components for the asciidoc package.
Group: Default
Requires: asciidoc-python3 = %{version}-%{release}

%description python
python components for the asciidoc package.


%package python3
Summary: python3 components for the asciidoc package.
Group: Default
Requires: python3-core
Provides: pypi(asciidoc)

%description python3
python3 components for the asciidoc package.


%prep
%setup -q -n asciidoc-10.1.4
cd %{_builddir}/asciidoc-10.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646768532
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/a2x
/usr/bin/asciidoc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
